/**
 * docker deployment adapter (LOU-I4).
 *
 * A thin wrapper over NodeServerAdapter: scaffold() and build() delegate to
 * it (the same server.ts/agent.config.js/package.json and the same bundled
 * dist/server.js), and scaffold() additionally writes a Dockerfile (plus a
 * .dockerignore) that packages dist/ into a node:22-slim image (22 has the node:sqlite that LOUSHO_STORE=sqlite:<path> needs).
 * describe(): 'docker build -t lousho-agent . && docker run -p 3000:3000 lousho-agent'.
 *
 * The image sets HOST=0.0.0.0: inside a container, the server's default
 * 127.0.0.1 binding would be unreachable through `docker run -p`, so the
 * image explicitly opts in to all-interfaces binding (the network boundary
 * is then the container's published port, chosen by whoever runs it).
 */
import * as path from 'node:path';
import { DeploymentAdapter, DeployOptions } from '../types';
import { writeFile } from '../bundle';
import { NodeServerAdapter } from './node-server';

export const DOCKERFILE = `# Generated by \`lousho build --target=docker\`.
FROM node:22-slim
WORKDIR /app
COPY package.json ./
RUN npm install --omit=dev
COPY dist/ ./dist/
ENV NODE_ENV=production
# Listen on all interfaces inside the container so \`docker run -p\` can reach it.
ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000
CMD ["node", "dist/server.js"]
`;

const DOCKERIGNORE = `node_modules
server.ts
agent.config.js
`;

export const DockerAdapter: DeploymentAdapter = {
  async scaffold(agentPath: string, outDir: string, options?: DeployOptions): Promise<void> {
    await NodeServerAdapter.scaffold(agentPath, outDir, options);
    writeFile(path.join(outDir, 'Dockerfile'), DOCKERFILE);
    writeFile(path.join(outDir, '.dockerignore'), DOCKERIGNORE);
  },

  async build(outDir: string): Promise<void> {
    await NodeServerAdapter.build(outDir);
  },

  describe(): string {
    return 'docker build -t lousho-agent . && docker run -p 3000:3000 lousho-agent';
  },
};
