/**
 * node-server deployment adapter (LOU-I2).
 *
 * scaffold(): loads + validates the agent spec at agentPath (the same
 *   .yaml/.yml/.json AgentSpec format `loushy dev` serves, via LOU-H9's
 *   loadSpec()), then writes:
 *     - agent.config.js  the validated spec, as an ES module default export
 *     - server.ts        starts the SDK's node server (src/deploy/nodeServer.ts):
 *                        GET /health plus the `loushy dev` /chat API (sessions,
 *                        SSE, approvals; LOU-D14), bearer auth via LOUSHY_API_TOKEN
 *     - package.json     minimal manifest with a `start` script
 * build():    bundles server.ts (+ agent.config.js + the SDK runtime) with
 *             tsup into a single self-contained dist/server.js.
 * describe(): 'node dist/server.js'.
 *
 * The generated server mirrors src/cli/dev.ts's security properties: it
 * binds to 127.0.0.1 unless a host is explicitly opted into (--host=<h> or
 * HOST=<h>), and caps POST bodies at 1MB (413 beyond that).
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { DeploymentAdapter, DeployOptions } from '../types';
import { loadSpec } from '../../spec/loadSpec';
import { AgentSpec } from '../../spec/schema';
import { resolveSpecTool } from '../../spec/specToAgent';
import { RUNTIME_SPECIFIER, loadTsup, sdkRuntimePlugin, writeFile } from '../bundle';

const SPEC_EXTENSIONS = new Set(['.yaml', '.yml', '.json']);

/**
 * Loads the agent config for a deployment target. Only declarative AgentSpec
 * files are supported: the repo's other agent "configs" (examples/*\/index.ts,
 * create-loushy-agent's src/agent.ts) are runnable scripts that call
 * createAgent() and immediately send a message, not importable configs.
 */
export function loadAgentSpecForDeploy(agentPath: string): AgentSpec {
  if (!agentPath) {
    throw new Error('--agent=<path> is required (an AgentSpec .yaml/.yml/.json file)');
  }
  if (!fs.existsSync(agentPath)) {
    throw new Error(`agent config not found: ${agentPath}`);
  }
  const ext = path.extname(agentPath).toLowerCase();
  if (!SPEC_EXTENSIONS.has(ext)) {
    throw new Error(
      `unsupported agent config '${agentPath}': expected an AgentSpec .yaml/.yml/.json file ` +
        `(the same format \`loushy dev\` loads)`
    );
  }
  return loadSpec(agentPath);
}

export function agentConfigModuleSource(spec: AgentSpec): string {
  return (
    `// Generated by \`loushy build\` from a validated AgentSpec. Edit the source spec and rebuild.\n` +
    `export default ${JSON.stringify(spec, null, 2)};\n`
  );
}

/** The generated server.ts: flags and listening here, the routes in the SDK runtime (src/deploy/nodeServer.ts). */
function serverSource(options: DeployOptions): string {
  return `/**
 * Generated by \`loushy build --target=node-server\`.
 *
 *   GET  /health                            -> 200 'ok'
 *   POST /chat                              -> { sessionId, input } in, the turn streamed as SSE out
 *                                              (the legacy { message } returns an ExecutionResult)
 *   GET  /chat/:sessionId                   -> the session's transcript
 *   POST /chat/:sessionId/approvals/:id     -> { approved, note? } or { answer }, streamed
 *
 * LOUSHY_API_TOKEN makes every route except /health require
 * 'Authorization: Bearer <token>'. LOUSHY_STORE ('memory', the default, or
 * 'sqlite:<path>') chooses where sessions live.
 *
 * Binds to 127.0.0.1 by default; pass --host=<h> (or HOST=<h>) to opt in to
 * listening on other interfaces. Port: --port=<n> / PORT, default 3000.
 */
import { agentSpecSchema, createDeployedAgent, createDeployedServer } from '${RUNTIME_SPECIFIER}';
import agentConfig from './agent.config.js';

function readFlag(name: string): string | undefined {
  const argv = process.argv.slice(2);
  const flag = argv.find((arg) => arg === '--' + name || arg.startsWith('--' + name + '='));
  if (!flag) return undefined;
  return flag.split('=')[1] || argv[argv.indexOf(flag) + 1];
}

const port = Number(readFlag('port') || process.env.PORT || 3000);
const host = readFlag('host') || process.env.HOST || '127.0.0.1';
const LOOPBACK = ['127.0.0.1', 'localhost', '::1'];

async function main(): Promise<void> {
  const agent = await createDeployedAgent(agentSpecSchema.parse(agentConfig));
  const { server, authenticated } = createDeployedServer(agent, ${JSON.stringify(options)});

  server.on('error', (err: NodeJS.ErrnoException) => {
    console.error(
      err.code === 'EADDRINUSE' ? '[loushy server] port ' + port + ' is already in use.' : err.message
    );
    process.exit(1);
  });

  server.listen(port, host, () => {
    const addr = server.address();
    const actualPort = addr && typeof addr === 'object' ? addr.port : port;
    console.log('loushy server: listening on http://' + host + ':' + actualPort);
    if (!authenticated && !LOOPBACK.includes(host)) {
      console.warn('[loushy server] warning: no LOUSHY_API_TOKEN set, so anyone who can reach ' + host + ' can use this agent.');
    }
  });

  for (const signal of ['SIGINT', 'SIGTERM'] as const) {
    process.once(signal, () => void agent.close().finally(() => process.exit(0)));
  }
}

main().catch((error: Error) => {
  console.error('[loushy server] failed to start: ' + error.message);
  process.exit(1);
});
`;
}

function packageJsonSource(spec: AgentSpec): string {
  const name = spec.name.toLowerCase().replace(/[^a-z0-9-_.]+/g, '-').replace(/^[-_.]+/, '') || 'loushy-agent';
  return (
    JSON.stringify(
      {
        name,
        version: '0.1.0',
        private: true,
        description: 'Deployable agent server generated by `loushy build`',
        scripts: { start: 'node dist/server.js' },
        // dist/server.js is fully bundled (SDK + deps included), so there
        // are no runtime dependencies to install.
        dependencies: {},
      },
      null,
      2
    ) + '\n'
  );
}

export const NodeServerAdapter: DeploymentAdapter = {
  async scaffold(agentPath: string, outDir: string, options: DeployOptions = {}): Promise<void> {
    const spec = loadAgentSpecForDeploy(agentPath);
    // Fail at build time, not at first request, on an unresolvable tool name.
    for (const tool of spec.tools || []) resolveSpecTool(tool);

    writeFile(path.join(outDir, 'agent.config.js'), agentConfigModuleSource(spec));
    writeFile(path.join(outDir, 'server.ts'), serverSource(options));
    writeFile(path.join(outDir, 'package.json'), packageJsonSource(spec));
  },

  async build(outDir: string): Promise<void> {
    const { build } = await loadTsup();
    await build({
      config: false,
      entry: { server: path.join(outDir, 'server.ts') },
      outDir: path.join(outDir, 'dist'),
      format: ['cjs'],
      platform: 'node',
      target: 'node18',
      outExtension: () => ({ js: '.js' }),
      // Bundle everything (SDK runtime + its deps) so dist/server.js runs
      // with no node_modules next to it.
      noExternal: [/.*/],
      esbuildPlugins: [sdkRuntimePlugin()],
      clean: true,
      splitting: false,
      sourcemap: false,
      dts: false,
      // Set LOUSHY_BUILD_VERBOSE=1 to see tsup's own build log (and full bundling errors).
      silent: !process.env.LOUSHY_BUILD_VERBOSE,
    });
  },

  describe(): string {
    return 'node dist/server.js';
  },
};

