/**
 * node-server deployment adapter (LOU-I2).
 *
 * scaffold(): loads + validates the agent spec at agentPath (the same
 *   .yaml/.yml/.json AgentSpec format `lousho dev` serves, via LOU-H9's
 *   loadSpec()), then writes:
 *     - agent.config.js  the validated spec, as an ES module default export
 *     - server.ts        starts the SDK's node server (src/deploy/nodeServer.ts):
 *                        GET /health plus the `lousho dev` /chat API (sessions,
 *                        SSE, approvals; LOU-D14), bearer auth via LOUSHO_API_TOKEN
 *     - package.json     manifest with a `start` script and the runtime
 *                        dependencies the built server needs (the SDK, the
 *                        spec's provider peer, the MCP SDK when mcpServers
 *                        are configured) - the docker image's `npm install`
 *   An agent directory (LOU-P8.2, see node-server-dir.ts) is accepted in place
 *   of a spec: server.ts then resolves it with resolveAgentDir() and starts
 *   its schedules and mounts its channels.
 * build():    bundles server.ts (+ agent.config.js + the SDK runtime) with
 *             tsup into a single self-contained dist/server.js.
 * describe(): 'node dist/server.js'.
 *
 * The generated server mirrors src/cli/dev.ts's security properties: it
 * binds to 127.0.0.1 unless a host is explicitly opted into (--host=<h> or
 * HOST=<h>), and caps POST bodies at 1MB (413 beyond that).
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { createRequire } from 'node:module';
import { parse as parseYaml } from 'yaml';
import { DeploymentAdapter, DeployOptions } from '../types';
import { SDKError } from '../../execution/errors';
import { loadSpec } from '../../spec/loadSpec';
import { AgentSpec } from '../../spec/schema';
import { specSchedules } from '../../schedules/specSchedules';
import { resolveSpecTool } from '../../spec/specToAgent';
import { listProviders, type AiMajor } from '../../providers/providerSpec';
import { findConfigFile, isCodeConfigFile } from '../../agentDir/readConfig';
import { RUNTIME_SPECIFIER, buildBundle, bundleExternals, findSdkRoot, loadTsup, sdkRuntimePlugin, writeFile } from '../bundle';
import { agentDirEntries, copyAgentDirAssets, isAgentDir, scaffoldedAgentDir, writeAgentDirPointer } from './node-server-dir';

const SPEC_EXTENSIONS = new Set(['.yaml', '.yml', '.json']);

/**
 * Loads the agent config for a deployment target. Only declarative AgentSpec
 * files are supported: the repo's other agent "configs" (examples/*\/index.ts,
 * create-lousho-agent's src/agent.ts) are runnable scripts that call
 * createAgent() and immediately send a message, not importable configs.
 */
export function loadAgentSpecForDeploy(agentPath: string): AgentSpec {
  if (!agentPath) {
    throw new SDKError('--agent=<path> is required (an AgentSpec .yaml/.yml/.json file)', 'LOUSHO_DEPLOY_FAILED');
  }
  if (!fs.existsSync(agentPath)) {
    throw new SDKError(`agent config not found: ${agentPath}`, 'LOUSHO_DEPLOY_FAILED');
  }
  const ext = path.extname(agentPath).toLowerCase();
  if (!SPEC_EXTENSIONS.has(ext)) {
    throw new SDKError(
      `unsupported agent config '${agentPath}': expected an AgentSpec .yaml/.yml/.json file ` +
        `(the same format \`lousho dev\` loads)`,
      'LOUSHO_DEPLOY_FAILED'
    );
  }
  return loadSpec(agentPath);
}

export function agentConfigModuleSource(spec: AgentSpec): string {
  return (
    `// Generated by \`lousho build\` from a validated AgentSpec. Edit the source spec and rebuild.\n` +
    `export default ${JSON.stringify(spec, null, 2)};\n`
  );
}

/** The parts of server.ts that differ between a spec build and an agent-directory build. */
interface ServerVariant {
  imports: string;
  /** Statements that define `agent`. */
  boot: string;
  /** The options expression of `createDeployedServer(agent, ...)`. */
  options: string;
  /** Extra start-up lines, run once the server listens. */
  report: string;
}

function specVariant(options: DeployOptions): ServerVariant {
  return {
    imports: `import { agentSpecSchema, createDeployedAgent, createDeployedServer, specSchedules } from '${RUNTIME_SPECIFIER}';
import agentConfig from './agent.config.js';`,
    boot: `const spec = agentSpecSchema.parse(agentConfig);
  const agent = await createDeployedAgent(spec);
  const schedules = specSchedules(spec.triggers);`,
    options: `{ ...${JSON.stringify(options)}, schedules }`,
    report: `console.log('lousho server: schedules: ' + (schedules.map((s) => s.name).join(', ') || 'none'));`,
  };
}

/** An agent directory: dist/agent is resolved at start-up, its schedules start and its channels mount (see node-server-dir.ts). */
function agentDirVariant(options: DeployOptions): ServerVariant {
  return {
    imports: `import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createAgent, createDeployedServer, resolveAgentDir, storeFromEnv } from '${RUNTIME_SPECIFIER}';`,
    boot: `const resolved = await resolveAgentDir(path.join(path.dirname(fileURLToPath(import.meta.url)), 'agent'));
  // A 'store' the directory's config declares wins over the LOUSHO_STORE default; an explicit LOUSHO_STORE still wins.
  const store = process.env.LOUSHO_STORE === undefined ? (resolved.config.store ?? storeFromEnv()) : storeFromEnv();
  const agent = createAgent({ ...resolved.config, store });
  await agent.ready();`,
    // An agent directory's auth.ts (N10a) replaces the baked token; LOUSHO_API_TOKEN is appended to it.
    options: `{ ...${JSON.stringify(options)}, ...(resolved.auth ? { auth: resolved.auth } : {}), schedules: resolved.schedules, channels: resolved.channels }`,
    report: `console.log('lousho server: schedules: ' + (resolved.manifest.schedules.join(', ') || 'none') + '; channels: ' + (resolved.manifest.channels.join(', ') || 'none'));`,
  };
}

/** The generated server.ts: flags and listening here, the routes in the SDK runtime (src/deploy/nodeServer.ts). */
function serverSource(variant: ServerVariant): string {
  return `/**
 * Generated by \`lousho build --target=node-server\`.
 *
 *   GET  /health                            -> 200 'ok'
 *   POST /chat                              -> { sessionId, input } in, the turn streamed as SSE out
 *                                              (the legacy { message } returns an ExecutionResult)
 *   GET  /chat/:sessionId                   -> the session's transcript
 *   POST /chat/:sessionId/approvals/:id     -> { approved, note? } or { answer }, streamed
 *
 * LOUSHO_API_TOKEN makes every route except /health require
 * 'Authorization: Bearer <token>' (after the agent directory's auth.ts, if
 * it has one: see docs/auth.md). LOUSHO_STORE ('memory', the default, or
 * 'sqlite:<path>') chooses where sessions live.
 *
 * Binds to 127.0.0.1 by default; pass --host=<h> (or HOST=<h>) to opt in to
 * listening on other interfaces. Port: --port=<n> / PORT, default 3000.
 */
${variant.imports}

function readFlag(name: string): string | undefined {
  const argv = process.argv.slice(2);
  const flag = argv.find((arg) => arg === '--' + name || arg.startsWith('--' + name + '='));
  if (!flag) return undefined;
  return flag.split('=')[1] || argv[argv.indexOf(flag) + 1];
}

const port = Number(readFlag('port') || process.env.PORT || 3000);
const host = readFlag('host') || process.env.HOST || '127.0.0.1';
const LOOPBACK = ['127.0.0.1', 'localhost', '::1'];

async function main(): Promise<void> {
  ${variant.boot}
  const { server, authenticated } = createDeployedServer(agent, ${variant.options});

  server.on('error', (err: NodeJS.ErrnoException) => {
    console.error(
      err.code === 'EADDRINUSE' ? '[lousho server] port ' + port + ' is already in use.' : err.message
    );
    process.exit(1);
  });

  server.listen(port, host, () => {
    const addr = server.address();
    const actualPort = addr && typeof addr === 'object' ? addr.port : port;
    console.log('lousho server: listening on http://' + host + ':' + actualPort);
    ${variant.report}
    if (!authenticated && !LOOPBACK.includes(host)) {
      console.warn('[lousho server] warning: no LOUSHO_API_TOKEN set, so anyone who can reach ' + host + ' can use this agent.');
    }
  });

  for (const signal of ['SIGINT', 'SIGTERM'] as const) {
    process.once(signal, () => void agent.close().finally(() => process.exit(0)));
  }
}

main().catch((error: Error) => {
  console.error('[lousho server] failed to start: ' + error.message);
  process.exit(1);
});
`;
}

/** The `ai` major the SDK copy doing the build runs on (its bundled runtime calls it); 7 when unresolvable. */
function bundledAiMajor(sdkRoot: string): AiMajor {
  try {
    const require = createRequire(path.join(sdkRoot, 'noop.js'));
    const version = JSON.parse(fs.readFileSync(require.resolve('ai/package.json'), 'utf8')).version as string;
    const major = Number.parseInt(version, 10);
    return major === 4 || major === 6 ? major : 7;
  } catch {
    return 7;
  }
}

/** The provider prefix of a `provider/model` string, or of a bare provider name. */
function providerTypeOf(modelOrType: string | undefined): string | undefined {
  if (!modelOrType) return undefined;
  const slash = modelOrType.indexOf('/');
  return (slash > 0 ? modelOrType.slice(0, slash) : modelOrType).toLowerCase();
}

/** The `model` a directory's data config (agent.json/agent.yaml) names; undefined for a code config or none. */
async function agentDirModel(dir: string): Promise<string | undefined> {
  try {
    const file = await findConfigFile(dir);
    if (!file || isCodeConfigFile(file)) return undefined;
    const raw = fs.readFileSync(file, 'utf8');
    const config = (file.endsWith('.json') ? JSON.parse(raw) : parseYaml(raw)) as { model?: unknown };
    return typeof config.model === 'string' ? config.model : undefined;
  } catch {
    return undefined;
  }
}

/**
 * The runtime dependencies a built server needs (LOU-R20): `dist/server.js`
 * bundles the SDK and its required dependencies, but the SDK's optional peers
 * stay external (see bundleExternals()), so `npm install` where the server
 * runs - the docker image's `npm install --omit=dev` - must install the ones
 * the agent actually uses. That is the SDK itself (pinned to the version that
 * built it, which also pulls its required peers such as `ai`), the provider
 * package `providerType` resolves to (at the range pairing with the build's
 * `ai` major), and `@modelcontextprotocol/sdk` when the agent uses MCP
 * servers. An unknown provider type (e.g. a registered test provider) adds no
 * dependency.
 */
export function deployDependencies(providerType?: string, hasMcpServers = false): Record<string, string> {
  const sdkRoot = findSdkRoot();
  const pkg = JSON.parse(fs.readFileSync(path.join(sdkRoot, 'package.json'), 'utf8')) as {
    version: string;
    peerDependencies?: Record<string, string>;
  };
  // `^` so a scaffold made from an unpublished development version resolves to
  // the nearest published release (`npm install` inside the image cannot
  // install a version that was never pushed to the registry), the same
  // convention sync-version.mjs uses for the create-lousho-agent pin.
  const dependencies: Record<string, string> = { '@lousho/build-ai-agent': `^${pkg.version}` };
  const info = listProviders().find((p) => p.name === providerType);
  if (info) {
    const peer = info.peers[bundledAiMajor(sdkRoot)];
    dependencies[peer.name] = peer.range;
  }
  const mcpRange = hasMcpServers ? pkg.peerDependencies?.['@modelcontextprotocol/sdk'] : undefined;
  if (mcpRange) dependencies['@modelcontextprotocol/sdk'] = mcpRange;
  return dependencies;
}

function packageJsonSource(agentName: string, dependencies: Record<string, string>): string {
  const name = agentName.toLowerCase().replace(/[^a-z0-9-_.]+/g, '-').replace(/^[-_.]+/, '') || 'lousho-agent';
  return (
    JSON.stringify(
      {
        name,
        version: '0.1.0',
        private: true,
        description: 'Deployable agent server generated by `lousho build`',
        scripts: { start: 'node dist/server.js' },
        // dist/server.js bundles the SDK and its required deps; the optional
        // peers the agent uses stay external and are installed from here.
        dependencies,
      },
      null,
      2
    ) + '\n'
  );
}

async function scaffoldAgentDir(agentPath: string, outDir: string, options: DeployOptions): Promise<void> {
  writeAgentDirPointer(outDir, agentPath);
  writeFile(path.join(outDir, 'server.ts'), serverSource(agentDirVariant(options)));
  // A code config can name any provider; a data config's `model` ('openai/...') tells us the peer to ship.
  const model = await agentDirModel(agentPath);
  writeFile(path.join(outDir, 'package.json'), packageJsonSource(path.basename(agentPath), deployDependencies(providerTypeOf(model))));
}

export const NodeServerAdapter: DeploymentAdapter = {
  async scaffold(agentPath: string, outDir: string, options: DeployOptions = {}): Promise<void> {
    if (isAgentDir(agentPath)) return scaffoldAgentDir(agentPath, outDir, options);
    const spec = loadAgentSpecForDeploy(agentPath);
    // Fail at build time, not at first request, on an unresolvable tool name.
    for (const tool of spec.tools || []) resolveSpecTool(tool);
    // Same for a cron trigger without a cron expression or input (LOUSHO_SCHEDULE_INVALID).
    specSchedules(spec.triggers);

    writeAgentDirPointer(outDir, undefined);
    writeFile(path.join(outDir, 'agent.config.js'), agentConfigModuleSource(spec));
    writeFile(path.join(outDir, 'server.ts'), serverSource(specVariant(options)));
    writeFile(
      path.join(outDir, 'package.json'),
      packageJsonSource(spec.name, deployDependencies(providerTypeOf(spec.provider.type), Object.keys(spec.mcpServers ?? {}).length > 0))
    );
  },

  async build(outDir: string): Promise<void> {
    const { build } = await loadTsup();
    const source = scaffoldedAgentDir(outDir);
    const entry = { server: path.join(outDir, 'server.ts'), ...(source ? await agentDirEntries(source) : {}) };
    await buildBundle(build, {
      config: false,
      entry,
      outDir: path.join(outDir, 'dist'),
      // An agent directory is one ESM build with shared chunks (node-server-dir.ts); a spec is a single CJS file.
      format: [source ? 'esm' : 'cjs'],
      shims: source !== undefined,
      // Bundled CommonJS dependencies (yaml, ...) call require() on node built-ins.
      banner: source ? { js: "import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);" } : {},
      splitting: source !== undefined,
      platform: 'node',
      target: 'node18',
      outExtension: () => ({ js: '.js' }),
      // Bundle the SDK runtime and its deps so dist/server.js runs with no node_modules next to it,
      // except the SDK's optional peers (dockerode, provider packages, MCP, ...): they are imported
      // lazily and a missing one raises the SDK's coded missing-peer error where it is needed.
      ...bundleExternals(),
      esbuildPlugins: [sdkRuntimePlugin()],
      clean: true,
      sourcemap: false,
      dts: false,
      // Set LOUSHO_BUILD_VERBOSE=1 to see tsup's own build log (and full bundling errors).
      silent: !process.env.LOUSHO_BUILD_VERBOSE,
    }, outDir);
    if (source) copyAgentDirAssets(source, outDir);
  },

  describe(): string {
    return 'node dist/server.js';
  },
};

