/**
 * node-server deployment adapter (LOU-I2).
 *
 * scaffold(): loads + validates the agent spec at agentPath (the same
 *   .yaml/.yml/.json AgentSpec format `loushy dev` serves, via LOU-H9's
 *   loadSpec()), then writes:
 *     - agent.config.js  the validated spec, as an ES module default export
 *     - server.ts        a node:http server wrapping the static
 *                        AgentExecutor.execute() (GET /health, POST /chat)
 *     - package.json     minimal manifest with a `start` script
 * build():    bundles server.ts (+ agent.config.js + the SDK runtime) with
 *             tsup into a single self-contained dist/server.js.
 * describe(): 'node dist/server.js'.
 *
 * The generated server mirrors src/cli/dev.ts's security properties: it
 * binds to 127.0.0.1 unless a host is explicitly opted into (--host=<h> or
 * HOST=<h>), and caps POST /chat bodies at 1MB (413 beyond that).
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { DeploymentAdapter } from '../types';
import { loadSpec } from '../../spec/loadSpec';
import { AgentSpec } from '../../spec/schema';
import { resolveSpecTool } from '../../spec/specToAgent';
import { RUNTIME_SPECIFIER, loadTsup, sdkRuntimePlugin, writeFile } from '../bundle';

const SPEC_EXTENSIONS = new Set(['.yaml', '.yml', '.json']);

/**
 * Loads the agent config for a deployment target. Only declarative AgentSpec
 * files are supported: the repo's other agent "configs" (examples/*\/index.ts,
 * create-loushy-agent's src/agent.ts) are runnable scripts that call
 * createAgent() and immediately send a message, not importable configs.
 */
export function loadAgentSpecForDeploy(agentPath: string): AgentSpec {
  if (!agentPath) {
    throw new Error('--agent=<path> is required (an AgentSpec .yaml/.yml/.json file)');
  }
  if (!fs.existsSync(agentPath)) {
    throw new Error(`agent config not found: ${agentPath}`);
  }
  const ext = path.extname(agentPath).toLowerCase();
  if (!SPEC_EXTENSIONS.has(ext)) {
    throw new Error(
      `unsupported agent config '${agentPath}': expected an AgentSpec .yaml/.yml/.json file ` +
        `(the same format \`loushy dev\` loads)`
    );
  }
  return loadSpec(agentPath);
}

export function agentConfigModuleSource(spec: AgentSpec): string {
  return (
    `// Generated by \`loushy build\` from a validated AgentSpec. Edit the source spec and rebuild.\n` +
    `export default ${JSON.stringify(spec, null, 2)};\n`
  );
}

const SERVER_TS = `/**
 * Generated by \`loushy build --target=node-server\`.
 *
 *   GET  /health -> 200 'ok'
 *   POST /chat   -> { message } in, AgentExecutor.execute()'s ExecutionResult out
 *
 * Binds to 127.0.0.1 by default; pass --host=<h> (or HOST=<h>) to opt in to
 * listening on other interfaces. Port: --port=<n> / PORT, default 3000.
 */
import * as http from 'node:http';
import { AgentExecutor, agentSpecSchema, prepareSpec } from '${RUNTIME_SPECIFIER}';
import agentConfig from './agent.config.js';

const MAX_BODY_BYTES = 1024 * 1024; // 1MB, same cap as \`loushy dev\`

class PayloadTooLargeError extends Error {}

function readFlag(name: string): string | undefined {
  const argv = process.argv.slice(2);
  const flag = argv.find((arg) => arg === '--' + name || arg.startsWith('--' + name + '='));
  if (!flag) return undefined;
  return flag.split('=')[1] || argv[argv.indexOf(flag) + 1];
}

const spec = agentSpecSchema.parse(agentConfig);
const prepared = prepareSpec(spec);

function readBody(req: http.IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    let body = '';
    let bytes = 0;
    let tooLarge = false;
    req.on('data', (chunk) => {
      bytes += chunk.length;
      if (bytes > MAX_BODY_BYTES) {
        // Keep draining (don't destroy) so the client can finish writing;
        // reject once the request ends.
        tooLarge = true;
        return;
      }
      body += chunk;
    });
    req.on('end', () => {
      if (tooLarge) {
        reject(new PayloadTooLargeError('Request body exceeds ' + MAX_BODY_BYTES + ' byte limit'));
        return;
      }
      resolve(body);
    });
    req.on('error', reject);
  });
}

function sendJson(res: http.ServerResponse, status: number, value: unknown): void {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(value));
}

async function handleRequest(req: http.IncomingMessage, res: http.ServerResponse): Promise<void> {
  if (req.method === 'GET' && req.url === '/health') {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end('ok');
    return;
  }

  if (req.method === 'POST' && req.url === '/chat') {
    try {
      const body = await readBody(req);
      const { message } = JSON.parse(body || '{}');
      if (typeof message !== 'string' || !message) {
        sendJson(res, 400, { error: "Request body must be JSON with a 'message' string" });
        return;
      }
      const result = await AgentExecutor.execute({ ...prepared, input: message });
      sendJson(res, 200, result);
    } catch (error) {
      if (error instanceof PayloadTooLargeError) {
        sendJson(res, 413, { error: error.message });
        return;
      }
      sendJson(res, 500, { error: (error as Error).message });
    }
    return;
  }

  res.writeHead(404, { 'Content-Type': 'text/plain' });
  res.end('not found');
}

const port = Number(readFlag('port') || process.env.PORT || 3000);
const host = readFlag('host') || process.env.HOST || '127.0.0.1';

const server = http.createServer((req, res) => {
  handleRequest(req, res).catch((error) => {
    console.error('[loushy server] unhandled request error:', error);
    if (!res.headersSent) res.writeHead(500);
    res.end();
  });
});

server.on('error', (err: NodeJS.ErrnoException) => {
  console.error(
    err.code === 'EADDRINUSE' ? '[loushy server] port ' + port + ' is already in use.' : err.message
  );
  process.exit(1);
});

server.listen(port, host, () => {
  const addr = server.address();
  const actualPort = addr && typeof addr === 'object' ? addr.port : port;
  console.log('loushy server: listening on http://' + host + ':' + actualPort);
});
`;

function packageJsonSource(spec: AgentSpec): string {
  const name = spec.name.toLowerCase().replace(/[^a-z0-9-_.]+/g, '-').replace(/^[-_.]+/, '') || 'loushy-agent';
  return (
    JSON.stringify(
      {
        name,
        version: '0.1.0',
        private: true,
        description: 'Deployable agent server generated by `loushy build`',
        scripts: { start: 'node dist/server.js' },
        // dist/server.js is fully bundled (SDK + deps included), so there
        // are no runtime dependencies to install.
        dependencies: {},
      },
      null,
      2
    ) + '\n'
  );
}

export const NodeServerAdapter: DeploymentAdapter = {
  async scaffold(agentPath: string, outDir: string): Promise<void> {
    const spec = loadAgentSpecForDeploy(agentPath);
    // Fail at build time, not at first request, on an unresolvable tool name.
    for (const tool of spec.tools || []) resolveSpecTool(tool);

    writeFile(path.join(outDir, 'agent.config.js'), agentConfigModuleSource(spec));
    writeFile(path.join(outDir, 'server.ts'), SERVER_TS);
    writeFile(path.join(outDir, 'package.json'), packageJsonSource(spec));
  },

  async build(outDir: string): Promise<void> {
    const { build } = await loadTsup();
    await build({
      config: false,
      entry: { server: path.join(outDir, 'server.ts') },
      outDir: path.join(outDir, 'dist'),
      format: ['cjs'],
      platform: 'node',
      target: 'node18',
      outExtension: () => ({ js: '.js' }),
      // Bundle everything (SDK runtime + its deps) so dist/server.js runs
      // with no node_modules next to it.
      noExternal: [/.*/],
      esbuildPlugins: [sdkRuntimePlugin()],
      clean: true,
      splitting: false,
      sourcemap: false,
      dts: false,
      // Set LOUSHY_BUILD_VERBOSE=1 to see tsup's own build log (and full bundling errors).
      silent: !process.env.LOUSHY_BUILD_VERBOSE,
    });
  },

  describe(): string {
    return 'node dist/server.js';
  },
};

