/**
 * Tracing
 * Minimal, exporter-agnostic span tracking for AgentExecutor runs
 * (LOU-E3/E4/E5).
 *
 * This intentionally does not depend on @opentelemetry/api or any other
 * tracing library - it is a small internal Span/TraceExporter abstraction
 * that a consumer can bridge into OpenTelemetry (or anything else) by
 * implementing TraceExporter themselves. See examples/tracing/ (LOU-E6)
 * for a console bridge and a real OTel bridge.
 */

import { newId } from '../utils/id';
import { ErrorAttr, GenAiAttr, LegacyAttr, SdkAttr } from './semconv';

/** OpenTelemetry span kind, for the kinds this SDK emits. */
export type SpanKind = 'internal' | 'client';

/** Span outcome; maps to OpenTelemetry's span status. */
export interface SpanStatus {
  code: 'ok' | 'error';
  message?: string;
}

/**
 * A single span of work.
 */
export interface Span {
  /** Unique id for this span, generated by withSpan(). */
  id: string;
  name: string;
  attributes: Record<string, unknown>;
  startTime: number;
  endTime?: number;
  parentId?: string;
  /** Defaults to `internal` when omitted. */
  kind?: SpanKind;
  /** Set to `{ code: 'error' }` when the span's work failed. */
  status?: SpanStatus;
}

/**
 * Records a failure on `span`: `error.type` (a low-cardinality class, the
 * error's name), the legacy `error` message attribute, and an error status.
 */
export function recordSpanError(span: Span, error: unknown): void {
  span.attributes = {
    ...span.attributes,
    [LegacyAttr.ERROR]: error instanceof Error ? error.message : error,
    [ErrorAttr.TYPE]: error instanceof Error ? error.name : ErrorAttr.OTHER,
  };
  span.status = { code: 'error', message: error instanceof Error ? error.message : String(error) };
}

/** Cost and estimation of the finished child spans of one open span (LOU-D48). */
interface UsageRollup {
  costUsd: number;
  /** At least one finished child carried a cost. */
  priced: boolean;
  /** A finished child had token usage but no known price. */
  unpriced: boolean;
  estimated: boolean;
}

/**
 * One span tracked for the rollup. An ended span stays here while it still
 * has open descendants, so a span that outlives its parent (a background
 * sub-agent's run, whose `task` tool span has already ended) can still find
 * the nearest open ancestor (Eve MA-F2).
 */
interface RollupNode {
  rollup: UsageRollup;
  parentId?: string;
  open: boolean;
  openChildren: number;
}

/** Spans by id: open ones, and ended ones with open descendants. */
const nodes = new Map<string, RollupNode>();

function track(span: Span, rollup: UsageRollup): void {
  nodes.set(span.id, { rollup, parentId: span.parentId, open: true, openChildren: 0 });
  const parent = span.parentId ? nodes.get(span.parentId) : undefined;
  if (parent) parent.openChildren += 1;
}

/** Marks a span ended and drops it, and any ended ancestors it kept alive, once nothing below is open. */
function untrack(id: string): void {
  const node = nodes.get(id);
  if (!node) return;
  node.open = false;
  let current: RollupNode | undefined = node;
  let currentId = id;
  while (current && !current.open && current.openChildren === 0) {
    nodes.delete(currentId);
    if (!current.parentId) break;
    const parent = nodes.get(current.parentId);
    if (parent) parent.openChildren -= 1;
    currentId = current.parentId;
    current = parent;
  }
}

/** The rollup of the nearest still-open ancestor of `span`. */
function openAncestor(span: Span): UsageRollup | undefined {
  let id = span.parentId;
  while (id) {
    const node = nodes.get(id);
    if (!node) return undefined;
    if (node.open) return node.rollup;
    id = node.parentId;
  }
  return undefined;
}

/**
 * Adds a finished span's usage to its nearest open ancestor's rollup (its
 * parent, unless the parent already ended): its `lousho.cost_usd` (or, with
 * tokens but no price, marks the ancestor as unpriced), and whether any of it
 * was estimated.
 */
function rollUpUsage(span: Span, own: UsageRollup): void {
  const parent = openAncestor(span);
  if (!parent) return;
  const cost = span.attributes[SdkAttr.COST_USD];
  if (typeof cost === 'number') {
    parent.costUsd += cost;
    parent.priced = true;
  } else if (span.attributes[GenAiAttr.USAGE_INPUT_TOKENS] !== undefined || own.unpriced) {
    parent.unpriced = true;
  }
  if (span.attributes[SdkAttr.USAGE_ESTIMATED] === true) parent.estimated = true;
}

/** Stamps the cumulative cost (and estimated flag) of a span's children onto it. */
function applyRollup(span: Span, own: UsageRollup): void {
  const priced = own.priced && !own.unpriced;
  if (!priced && !own.estimated) return;
  span.attributes = {
    ...span.attributes,
    ...(priced ? { [SdkAttr.COST_USD]: own.costUsd } : {}),
    ...(own.estimated ? { [SdkAttr.USAGE_ESTIMATED]: true } : {}),
  };
}

/**
 * Receives span lifecycle notifications. No default implementation ships
 * in this SDK - consumers bridge onSpanStart/onSpanEnd into whatever
 * tracing backend they use (console, OpenTelemetry, Datadog, ...).
 */
export interface TraceExporter {
  onSpanStart(span: Span): void;
  onSpanEnd(span: Span): void;
}

/**
 * Runs `fn` inside a span named `name` with the given `attributes`,
 * notifying `exporter` (if provided) on start and end.
 *
 * - When no exporter is supplied, `fn` still runs normally and withSpan()
 *   never throws on account of the missing exporter.
 * - `onSpanEnd` always fires via a `finally` block, even when `fn` throws.
 *   On error, an `error` attribute (the error's message, or the error
 *   itself when it's not an Error) is added to the span's attributes
 *   before `onSpanEnd` is invoked, and the original error is then
 *   rethrown unchanged. The span also gets `error.type` and an error
 *   `status` (see {@link recordSpanError}).
 * - `parentId` lets callers thread parent/child span relationships
 *   (LOU-E5 uses this to nest `llm.generate`/`tool.call` spans under a
 *   top-level `agent.run` span).
 * - `fn` receives the span so callers can read its generated `id` (e.g.
 *   to pass as the `parentId` of a further-nested withSpan() call).
 * - `kind` is the OpenTelemetry span kind (default `internal`).
 * - Before `onSpanEnd`, a span whose child spans carried `lousho.cost_usd`
 *   gets the sum as its own (cumulative) `lousho.cost_usd`, absent when a
 *   child with token usage had no known price, and `lousho.usage.estimated`
 *   when any child's tokens were estimated (LOU-D48). A span that ends after
 *   its parent adds to the nearest ancestor still open instead.
 */
export async function withSpan<T>(
  exporter: TraceExporter | undefined,
  name: string,
  attributes: Record<string, unknown>,
  fn: (span: Span) => Promise<T>,
  parentId?: string,
  kind?: SpanKind
): Promise<T> {
  const span: Span = {
    id: newId(),
    name,
    attributes,
    startTime: Date.now(),
    parentId,
    ...(kind ? { kind } : {}),
  };

  const own: UsageRollup = { costUsd: 0, priced: false, unpriced: false, estimated: false };
  track(span, own);
  exporter?.onSpanStart(span);

  try {
    return await fn(span);
  } catch (error) {
    recordSpanError(span, error);
    throw error;
  } finally {
    span.endTime = Date.now();
    applyRollup(span, own);
    rollUpUsage(span, own);
    untrack(span.id);
    exporter?.onSpanEnd(span);
  }
}
