/**
 * Tracing
 * Minimal, exporter-agnostic span tracking for AgentExecutor runs
 * (LOU-E3/E4/E5).
 *
 * This intentionally does not depend on @opentelemetry/api or any other
 * tracing library - it is a small internal Span/TraceExporter abstraction
 * that a consumer can bridge into OpenTelemetry (or anything else) by
 * implementing TraceExporter themselves. See examples/tracing/ (LOU-E6)
 * for a console bridge and a real OTel bridge.
 */

import { nanoid } from 'nanoid';
import { ErrorAttr, LegacyAttr } from './semconv';

/** OpenTelemetry span kind, for the kinds this SDK emits. */
export type SpanKind = 'internal' | 'client';

/** Span outcome; maps to OpenTelemetry's span status. */
export interface SpanStatus {
  code: 'ok' | 'error';
  message?: string;
}

/**
 * A single span of work.
 */
export interface Span {
  /** Unique id for this span, generated by withSpan(). */
  id: string;
  name: string;
  attributes: Record<string, unknown>;
  startTime: number;
  endTime?: number;
  parentId?: string;
  /** Defaults to `internal` when omitted. */
  kind?: SpanKind;
  /** Set to `{ code: 'error' }` when the span's work failed. */
  status?: SpanStatus;
}

/**
 * Records a failure on `span`: `error.type` (a low-cardinality class, the
 * error's name), the legacy `error` message attribute, and an error status.
 */
export function recordSpanError(span: Span, error: unknown): void {
  span.attributes = {
    ...span.attributes,
    [LegacyAttr.ERROR]: error instanceof Error ? error.message : error,
    [ErrorAttr.TYPE]: error instanceof Error ? error.name : ErrorAttr.OTHER,
  };
  span.status = { code: 'error', message: error instanceof Error ? error.message : String(error) };
}

/**
 * Receives span lifecycle notifications. No default implementation ships
 * in this SDK - consumers bridge onSpanStart/onSpanEnd into whatever
 * tracing backend they use (console, OpenTelemetry, Datadog, ...).
 */
export interface TraceExporter {
  onSpanStart(span: Span): void;
  onSpanEnd(span: Span): void;
}

/**
 * Runs `fn` inside a span named `name` with the given `attributes`,
 * notifying `exporter` (if provided) on start and end.
 *
 * - When no exporter is supplied, `fn` still runs normally and withSpan()
 *   never throws on account of the missing exporter.
 * - `onSpanEnd` always fires via a `finally` block, even when `fn` throws.
 *   On error, an `error` attribute (the error's message, or the error
 *   itself when it's not an Error) is added to the span's attributes
 *   before `onSpanEnd` is invoked, and the original error is then
 *   rethrown unchanged. The span also gets `error.type` and an error
 *   `status` (see {@link recordSpanError}).
 * - `parentId` lets callers thread parent/child span relationships
 *   (LOU-E5 uses this to nest `llm.generate`/`tool.call` spans under a
 *   top-level `agent.run` span).
 * - `fn` receives the span so callers can read its generated `id` (e.g.
 *   to pass as the `parentId` of a further-nested withSpan() call).
 * - `kind` is the OpenTelemetry span kind (default `internal`).
 */
export async function withSpan<T>(
  exporter: TraceExporter | undefined,
  name: string,
  attributes: Record<string, unknown>,
  fn: (span: Span) => Promise<T>,
  parentId?: string,
  kind?: SpanKind
): Promise<T> {
  const span: Span = {
    id: nanoid(),
    name,
    attributes,
    startTime: Date.now(),
    parentId,
    ...(kind ? { kind } : {}),
  };

  exporter?.onSpanStart(span);

  try {
    return await fn(span);
  } catch (error) {
    recordSpanError(span, error);
    throw error;
  } finally {
    span.endTime = Date.now();
    exporter?.onSpanEnd(span);
  }
}
